### ISSUE TITLE
Error while importing wafv2

### ISSUE THREAD

**Issue by tribu** [aws-samples/aws2tf#104]
I am getting error  in get_aws_wafv2_web_acl_logging_configuration. I have tried to import excluding logging configuration and still get the same error.

```
./aws2tf.py -t wafv2 --region us-east-1Logical cores: 10
STATUS: 0s elapsed aws2tf: Starting, update messages every 20 seconds
aws2tf started at 2025-03-19 09:33:03.949871
boto3 version:  1.36.13
Terraform version 1.9.8
account=XXXXXXXXXXXX
Using region: us-east-1 account: XXXXXXXXXXXX profile: default

terraform init
STATUS: 20s elapsed Stage 1 of 10, Terraform Initialise ...
PASSED: Terraform Initialise OK
build lists started at 2025-03-19 09:33:03.949871
Building core resource lists ...
build lists finished at 2025-03-19 09:33:30.251764
build lists took 0:00:02.862390
---<><> wafv2 Id=None  exclude=[]
all_types=['aws_wafv2_web_acl', 'aws_wafv2_ip_set', 'aws_wafv2_rule_group']
len all_types=3
INFO: Getting Regional resources
Known Dependancies - Multi Threaded
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
STATUS: 40s elapsed Stage 4 of 10, Known Dependancies: moving files

aws2tf Detected Dependancies started at 2025-03-19 09:33:44.437357


ERROR: in get_aws_wafv2_web_acl_logging_configuration clfn=wafv2 descfn=get_logging_configuration topkey=LoggingConfiguration id=arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
e=WAFNonexistentItemException('An error occurred (WAFNonexistentItemException) when calling the GetLoggingConfiguration operation: AWS WAF couldn’t perform the operation because your resource doesn’t exist.') [e1]
exn='WAFNonexistentItemException' [e1]
aws_wafv2.py 214
stopping process ...

```

with exclude
```
 ./aws2tf.py -t wafv2 --exclude aws_wafv2_web_acl_logging_configuration --region us-east-1
Logical cores: 10
STATUS: 0s elapsed aws2tf: Starting, update messages every 20 seconds
aws2tf started at 2025-03-19 09:21:03.348223
boto3 version:  1.36.13
Terraform version 1.9.8
region set from aws cli / environment variables as ap-south-1
account=XXXXXXXXXXXX
Using region: ap-south-1 account: XXXXXXXXXXXX profile: default

terraform init
STATUS: 20s elapsed Stage 1 of 10, Terraform Initialise ...
PASSED: Terraform Initialise OK
build lists started at 2025-03-19 09:21:03.348223
Building core resource lists ...
build lists finished at 2025-03-19 09:21:39.008707
build lists took 0:00:06.699657
---<><> wafv2 Id=None  exclude=['aws_wafv2_web_acl_logging_configuration']
all_types=['aws_wafv2_web_acl', 'aws_wafv2_ip_set', 'aws_wafv2_rule_group']
len all_types=3
WARNING:Can only import CLOUDFRONT web ACL's from us-east-1 region
WARNING:Can only import CLOUDFRONT ip sets from us-east-1 region
INFO: Getting Regional resources
WARNING:Can only import CLOUDFRONT web ACL's from us-east-1 region
Known Dependancies - Multi Threaded
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
STATUS: 40s elapsed Stage 4 of 10, Known Dependancies: terraform plan
cd ~/workspace/git/aws2tfSTATUS: 60s elapsed Stage 4 of 10, Known Dependancies: terraform plan
^R
STATUS: 80s elapsed Stage 4 of 10, Known Dependancies: terraform plan

aws2tf Detected Dependancies started at 2025-03-19 09:22:38.864900

Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Terraform Plan - Dependancies Detection Loop 1.....
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
STATUS: 100s elapsed Stage 6 of 10, Dependancies Detection: Loop 1 terraform plan
^[[ASTATUS: 120s elapsed Stage 6 of 10, Dependancies Detection: Loop 1 terraform plan
STATUS: 140s elapsed Stage 6 of 10, Dependancies Detection: Loop 1 terraform plan

----------- Completed 1 dependancy check loops --------------
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Excluding aws_wafv2_web_acl_logging_configuration
Terraform Plan - Dependancies Detection Loop 2.....
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
STATUS: 160s elapsed Stage 6 of 10, Dependancies Detection: Loop 2 terraform plan
STATUS: 180s elapsed Stage 6 of 10, Dependancies Detection: Loop 2 terraform plan
STATUS: 200s elapsed Stage 6 of 10, Dependancies Detection: Loop 2 terraform plan

----------- Completed 2 dependancy check loops --------------

ERROR: No change/progress in dependancies exiting...

ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/MerchantDashboardWAF/b1c09abc-a8e3-4259-a7a0-9924cac8a379 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/PG-API-Gocashfree/b599281d-0053-4b3a-af99-03fb89e9780d - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/PG-API-Rules/95e5d7ed-d040-420a-afe5-a4def900380d - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/PG-Security/28c1e90a-2991-4031-81ec-821350f94d59 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/PayoutGamma/b9a18c2b-c383-434f-b705-aa422b58f924 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/cashfree-com/8981ace8-55bc-4027-89d8-d3e92225f212 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/gamma-alb-waf/0affe8fd-a278-4703-a79d-9fb8a9f72ca7 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/gamma-t1/53f135ef-bf2c-4b41-a4aa-fbce35e049cd - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/goCash-LB/c0894790-cbfd-4f2c-be10-89235c934c7e - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/payout-api/cd019e28-7e9e-41ea-9bb4-9749d12f83d1 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:ap-south-1:XXXXXXXXXXXX:regional/webacl/test-gamma-ddos/de58984a-fcbb-4990-82c4-bf55ab21ef8f - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory

```

Further, I have tried with multiple versions of terraform 1.9.8 to 1.11.1

**Comment by awsandy** [comment]
committed changes that should fix this.

**Comment by tribu** [comment]
Still having issues

```
./aws2tf.py -t wafv2 --exclude aws_wafv2_web_acl_logging_configuration --region=us-east-1 --debug
Logical cores: 10
STATUS: 0s elapsed aws2tf: Starting, update messages every 20 seconds
aws2tf started at 2025-03-20 22:46:33.888519
boto3 version:  1.36.13
Terraform version 1.9.8
setting session region=us-east-1
getting account
account=XXXXXXXXXXXX
Using region: us-east-1 account: XXXXXXXXXXXX profile: default

terraform init
Initializing the backend...
Initializing provider plugins...
- Finding hashicorp/aws versions matching "5.86.0"...
- Installing hashicorp/aws v5.86.0...
- Installed hashicorp/aws v5.86.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
PASSED: Terraform Initialise OK
build lists started at 2025-03-20 22:46:33.888519
Building core resource lists ...
build lists finished at 2025-03-20 22:46:53.571035
build lists took 0:00:03.053321
---<><> wafv2 Id=None  exclude=['aws_wafv2_web_acl_logging_configuration']
all_types=['aws_wafv2_web_acl', 'aws_wafv2_ip_set', 'aws_wafv2_rule_group']
len all_types=3
1 of 3	aws_wafv2_web_acl
---->>>>> aws_wafv2_web_acl   None
calling specific common.get_aws_wafv2_web_acl with type=aws_wafv2_web_acl id=None   clfn=wafv2 descfn=list_web_acls topkey=WebACLs  key=WebACLId  filterid=WebACLId
--> In get_aws_wafv2_web_acl doing aws_wafv2_web_acl with id None clfn=wafv2 descfn=list_web_acls topkey=WebACLs key=WebACLId filterid=WebACLId
STATUS: 20s elapsed Stage 3 of 10, 1 of 3 resource types 	 currently getting aws_wafv2_web_acl
import__aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.tf
add_dependancy: aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
Empty response for aws_wafv2_web_acl Scope=REGIONAL returning
{'WebACLs': [], 'ResponseMetadata': {'RequestId': '10452eb6-f578-4837-8311-fd9029868d20', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '10452eb6-f578-4837-8311-fd9029868d20', 'content-type': 'application/x-amz-json-1.1', 'content-length': '14', 'date': 'Thu, 20 Mar 2025 17:16:54 GMT'}, 'RetryAttempts': 0}}
2 of 3	aws_wafv2_ip_set
---->>>>> aws_wafv2_ip_set   None
calling specific common.get_aws_wafv2_ip_set with type=aws_wafv2_ip_set id=None   clfn=wafv2 descfn=list_ip_sets topkey=IPSets  key=IPSetId  filterid=IPSetId
--> In get_aws_wafv2_ip_set doing aws_wafv2_ip_set with id None clfn=wafv2 descfn=list_ip_sets topkey=IPSets key=IPSetId filterid=IPSetId
INFO: Getting Regional resources
Empty response for aws_wafv2_ip_set Scope=REGIONAL returning
{'IPSets': [], 'ResponseMetadata': {'RequestId': '762fe317-4c98-41d8-94f6-XXXXXXXXXXX', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '762fe317-4c98-41d8-94f6-XXXXXXXXXXX', 'content-type': 'application/x-amz-json-1.1', 'content-length': '13', 'date': 'Thu, 20 Mar 2025 17:16:56 GMT'}, 'RetryAttempts': 0}}
3 of 3	aws_wafv2_rule_group
---->>>>> aws_wafv2_rule_group   None
calling specific common.get_aws_wafv2_rule_group with type=aws_wafv2_rule_group id=None   clfn=wafv2 descfn=list_rule_groups topkey=RuleGroups  key=RuleGroupId  filterid=RuleGroupId
--> In get_aws_wafv2_rule_group doing aws_wafv2_rule_group with id None clfn=wafv2 descfn=list_rule_groups topkey=RuleGroups key=RuleGroupId filterid=RuleGroupId
Empty response for aws_wafv2_rule_group Scope=REGIONAL returning
{'RuleGroups': [], 'ResponseMetadata': {'RequestId': 'c581c7aa-55c1-4cdb-9d7b-074affb7dc1c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'c581c7aa-55c1-4cdb-9d7b-074affb7dc1c', 'content-type': 'application/x-amz-json-1.1', 'content-length': '17', 'date': 'Thu, 20 Mar 2025 17:16:57 GMT'}, 'RetryAttempts': 0}}
Known Dependancies - Multi Threaded
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
split file: resources.out
processing aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.tf
aws_wafv2_web_acl fixtf aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.out
callfn=fixtf_wafv2 ttft=aws_wafv2_web_acl

aws2tf Detected Dependancies started at 2025-03-20 22:47:08.989901

aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
DD calling getresource with type=aws_wafv2_web_acl_logging_configuration id=arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
Excluding: aws_wafv2_web_acl_logging_configuration
Terraform Plan - Dependancies Detection Loop 1.....
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
STATUS: 40s elapsed Stage 6 of 10, Dependancies Detection: Loop 1 terraform plan
split file: resources.out
File exists: aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.tf skipping ...

----------- Completed 1 dependancy check loops --------------
DD calling getresource with type=aws_wafv2_web_acl_logging_configuration id=arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
Excluding: aws_wafv2_web_acl_logging_configuration
Terraform Plan - Dependancies Detection Loop 2.....
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
split file: resources.out
File exists: aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.tf skipping ...

----------- Completed 2 dependancy check loops --------------

ERROR: No change/progress in dependancies exiting...

ERROR: Not found aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62 - check if this resource still exists in AWS. Also check what resource is using it - grep the *.tf files in the generated/tf.* subdirectory
exit 011
```

**Comment by tribu** [comment]
Thanks for the changes
```
./aws2tf.py -t wafv2 --exclude aws_wafv2_web_acl --region=ap-south-1 
```
is working  and the ipset is getting imported successfully

but still facing same error with **aws_wafv2_web_acl**

```
./aws2tf.py -t wafv2  --region=ap-south-1
Logical cores: 10
STATUS: 0s elapsed aws2tf: Starting, update messages every 20 seconds
aws2tf started at 2025-03-20 23:02:45.981351
boto3 version:  1.36.13
Terraform version 1.9.8
account=XXXXXXXXXXXX
Using region: ap-south-1 account: XXXXXXXXXXXX profile: default

terraform init
STATUS: 20s elapsed Stage 1 of 10, Terraform Initialise ...
PASSED: Terraform Initialise OK
build lists started at 2025-03-20 23:02:45.981351
Building core resource lists ...
build lists finished at 2025-03-20 23:03:25.576134
build lists took 0:00:02.919080
---<><> wafv2 Id=None  exclude=[]
all_types=['aws_wafv2_web_acl', 'aws_wafv2_ip_set', 'aws_wafv2_rule_group']
len all_types=3
WARNING:Can only import CLOUDFRONT web ACL's from us-east-1 region
STATUS: 40s elapsed Stage 3 of 10, 1 of 3 resource types 	 currently getting aws_wafv2_web_acl
WARNING:Can only import CLOUDFRONT ip sets from us-east-1 region
INFO: Getting Regional resources
WARNING:Can only import CLOUDFRONT web ACL's from us-east-1 region
Known Dependancies - Multi Threaded
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json

aws2tf Detected Dependancies started at 2025-03-20 23:03:35.798987

Terraform Plan - Dependancies Detection Loop 1.....
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json

----------- Completed 1 dependancy check loops --------------

Validate and Test Plan  ...

Error: Conflicting configuration arguments

  with aws_wafv2_web_acl.w-00101864-2e70-442e-a284-c4eed577500d_cf-qa-cashfree_REGIONAL,
  on aws_wafv2_web_acl__w-00101864-2e70-442e-a284-c4eed577500d_cf-qa-cashfree_REGIONAL.tf line 5, in resource "aws_wafv2_web_acl" "w-00101864-2e70-442e-a284-c4eed577500d_cf-qa-cashfree_REGIONAL":
   5:   rule_json   = file("w-00101864-2e70-442e-a284-c4eed577500d_cf-qa-cashfree_REGIONAL.webacl")

"rule_json": conflicts with rule

Validation after fix failed - exiting
exit 020

```



another region with cloudfront



```
./aws2tf.py -t wafv2  --region=us-east-1 --debug
Logical cores: 10
STATUS: 0s elapsed aws2tf: Starting, update messages every 20 seconds
aws2tf started at 2025-03-20 23:04:17.200979
boto3 version:  1.36.13
Terraform version 1.9.8
setting session region=us-east-1
getting account
account=XXXXXXXXXXXX
Using region: us-east-1 account: XXXXXXXXXXXX profile: default

terraform init
Initializing the backend...
Initializing provider plugins...
- Finding hashicorp/aws versions matching "5.86.0"...
- Installing hashicorp/aws v5.86.0...
- Installed hashicorp/aws v5.86.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
PASSED: Terraform Initialise OK
build lists started at 2025-03-20 23:04:17.200979
Building core resource lists ...
build lists finished at 2025-03-20 23:04:35.418441
build lists took 0:00:02.776331
---<><> wafv2 Id=None  exclude=[]
all_types=['aws_wafv2_web_acl', 'aws_wafv2_ip_set', 'aws_wafv2_rule_group']
len all_types=3
1 of 3	aws_wafv2_web_acl
---->>>>> aws_wafv2_web_acl   None
calling specific common.get_aws_wafv2_web_acl with type=aws_wafv2_web_acl id=None   clfn=wafv2 descfn=list_web_acls topkey=WebACLs  key=WebACLId  filterid=WebACLId
--> In get_aws_wafv2_web_acl doing aws_wafv2_web_acl with id None clfn=wafv2 descfn=list_web_acls topkey=WebACLs key=WebACLId filterid=WebACLId
import__aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.tf
add_dependancy: aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
Empty response for aws_wafv2_web_acl Scope=REGIONAL returning
{'WebACLs': [], 'ResponseMetadata': {'RequestId': '7755f86c-8d5b-4ac1-b6a5-36bce1c17e08', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '7755f86c-8d5b-4ac1-b6a5-36bce1c17e08', 'content-type': 'application/x-amz-json-1.1', 'content-length': '14', 'date': 'Thu, 20 Mar 2025 17:34:36 GMT'}, 'RetryAttempts': 0}}
2 of 3	aws_wafv2_ip_set
---->>>>> aws_wafv2_ip_set   None
calling specific common.get_aws_wafv2_ip_set with type=aws_wafv2_ip_set id=None   clfn=wafv2 descfn=list_ip_sets topkey=IPSets  key=IPSetId  filterid=IPSetId
--> In get_aws_wafv2_ip_set doing aws_wafv2_ip_set with id None clfn=wafv2 descfn=list_ip_sets topkey=IPSets key=IPSetId filterid=IPSetId
STATUS: 20s elapsed Stage 3 of 10, 2 of 3 resource types 	 currently getting aws_wafv2_ip_set
INFO: Getting Regional resources
Empty response for aws_wafv2_ip_set Scope=REGIONAL returning
{'IPSets': [], 'ResponseMetadata': {'RequestId': 'e38f1dce-9a8d-476b-ba0f-XXXXXXXXXXX', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'e38f1dce-9a8d-476b-ba0f-XXXXXXXXXXX', 'content-type': 'application/x-amz-json-1.1', 'content-length': '13', 'date': 'Thu, 20 Mar 2025 17:34:38 GMT'}, 'RetryAttempts': 0}}
3 of 3	aws_wafv2_rule_group
---->>>>> aws_wafv2_rule_group   None
calling specific common.get_aws_wafv2_rule_group with type=aws_wafv2_rule_group id=None   clfn=wafv2 descfn=list_rule_groups topkey=RuleGroups  key=RuleGroupId  filterid=RuleGroupId
--> In get_aws_wafv2_rule_group doing aws_wafv2_rule_group with id None clfn=wafv2 descfn=list_rule_groups topkey=RuleGroups key=RuleGroupId filterid=RuleGroupId
Empty response for aws_wafv2_rule_group Scope=REGIONAL returning
{'RuleGroups': [], 'ResponseMetadata': {'RequestId': 'b15d0caa-df7a-45e8-8f2e-XXXXXXXXXXXX', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'b15d0caa-df7a-45e8-8f2e-XXXXXXXXXXXX', 'content-type': 'application/x-amz-json-1.1', 'content-length': '17', 'date': 'Thu, 20 Mar 2025 17:34:39 GMT'}, 'RetryAttempts': 0}}
Known Dependancies - Multi Threaded
terraform plan -generate-config-out=resources.out -out tfplan -json > plan1.json
split file: resources.out
processing aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.tf
aws_wafv2_web_acl fixtf aws_wafv2_web_acl__w-d94b0d51-833f-4ae0-9ed0-af8f48b1dc62_CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9_CLOUDFRONT.out
callfn=fixtf_wafv2 ttft=aws_wafv2_web_acl

aws2tf Detected Dependancies started at 2025-03-20 23:04:50.952848

aws_wafv2_web_acl_logging_configuration.arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
DD calling getresource with type=aws_wafv2_web_acl_logging_configuration id=arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
---->>>>> aws_wafv2_web_acl_logging_configuration   arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
calling specific common.get_aws_wafv2_web_acl_logging_configuration with type=aws_wafv2_web_acl_logging_configuration id=arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62   clfn=wafv2 descfn=get_logging_configuration topkey=LoggingConfiguration  key=ResourceArn  filterid=ResourceArn
--> In get_aws_wafv2_web_acl_logging_configuration doing aws_wafv2_web_acl_logging_configuration with id arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62 clfn=wafv2 descfn=get_logging_configuration topkey=LoggingConfiguration key=ResourceArn filterid=ResourceArn

ERROR: in get_aws_wafv2_web_acl_logging_configuration clfn=wafv2 descfn=get_logging_configuration topkey=LoggingConfiguration id=arn:aws:wafv2:us-east-1:XXXXXXXXXXXX:global/webacl/CreatedByCloudFront-eca48f1c-6a5c-4e0e-aa71-94a49c4f0ba9/d94b0d51-833f-4ae0-9ed0-af8f48b1dc62
e=WAFNonexistentItemException('An error occurred (WAFNonexistentItemException) when calling the GetLoggingConfiguration operation: AWS WAF couldn’t perform the operation because your resource doesn’t exist.') [e1]
exn='WAFNonexistentItemException' [e1]
aws_wafv2.py 217
stopping process ...



```

**Comment by awsandy** [comment]
committed further changes to try and fix this

**Comment by tribu** [comment]
This worked like a charm.
Thanks !!!
