### ISSUE TITLE
Name,

### ISSUE THREAD

**Issue by jdonalson** [aws-samples/aws2tf#87]
ERROR: Not importing aws_secretsmanager_secret arn:aws:secretsmanager:us-east-1:xxxxx:secret:rds!cluster-36d996b5-5fe6-4775-889e-c2ef1fedb072-dC7gzB
ERROR: Invalid character ! in name

ERROR: in write_import
id=<built-in function id>

**Comment by awsandy** [comment]
committed changes that should fix this one.

**Comment by jdonalson** [comment]
<img width="1378" alt="Screenshot 2024-10-17 at 7 02 11 AM" src="https://github.com/user-attachments/assets/305a8562-98fe-4988-9424-3fd0ce4bae23">
unfortunately I think error persists; shall I give you debug output?

**Comment by awsandy** [comment]
secrets that are names beginning with rds!* are rds managed,  so they are now not imported as separate Terraform managed secrets.

Their creation is handled by an option when creating the rds resource itself.

So the fix implemented now is to detect when a secret name starts with rds! - if it does the import of the secret is skipped.
